version: '3.4'

services:
  messagepersistentservice:
    image: messagepersistentservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 6001:6001
