version: '3.4'

services:
  messagepersistentservice:
    image: messagepersistentservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6001:6001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
