# Development Compose For Authentication Services
version: '3.4'

services:
  mongodb-MessagePersist-Dev:
    image: mongo
    restart: always
    ports:
      - 6002:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo-express-MessagePersist-Dev:
    image: mongo-express
    restart: always
    ports: 
      - 6003:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb-MessagePersist-Dev
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
