# Development Compose For Authentication Services
version: '3.4'

services:
  mongodbDev:
    image: mongo
    restart: always
    ports:
      - 3002:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo-expressDev:
    image: mongo-express
    restart: always
    ports: 
      - 3003:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodbDev
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
